var jsPsych = initJsPsych({
    on_finish: function() {
        jsPsych.data.displayData();
    }
});

/*declare main timeline*/
var main_timeline = [];

/*Preload Media*/
var preload = {
    type: jsPsychPreload,
    images: [
        /*STAND ALONE FORMAT */
        'img/un.png',
        'img/af.png',
        'img/al.png',
        'img/dz.png',
        'img/ad.png',
        'img/ao.png',
        'img/ag.png',
        'img/ar.png',
        'img/am.png',
        'img/au.png',
        'img/at.png',
        'img/az.png',
        'img/bs.png', 
        'img/bh.png',
        'img/bd.png',
        'img/bb.png',
        'img/by.png',
        'img/be.png',
        'img/bz.png',
        'img/bj.png',
        'img/bt.png',
        'img/bo.png',
        'img/ba.png',
        'img/bw.png',
        'img/br.png',
        'img/bn.png',
        'img/bg.png',
        'img/bf.png',
        'img/bi.png',
        'img/kh.png',
        'img/cm.png',
        'img/ca.png',
        'img/cv.png',
        'img/cf.png',
        'img/td.png',
        'img/cl.png',
        'img/cn.png',
        'img/co.png',
        'img/km.png',
        'img/cg.png',
        'img/cd.png',
        'img/cr.png',
        'img/ci.png',
        'img/hr.png',
        'img/cu.png',
        'img/cy.png',
        'img/cz.png',
        'img/dk.png',
        'img/dj.png',
        'img/dm.png',
        'img/do.png',
        'img/ec.png',
        'img/eg.png',
        'img/sv.png',
        'img/gq.png',
        'img/er.png',
        'img/ee.png',
        'img/sz.png',
        'img/et.png',
        'img/fj.png',
        'img/fi.png',
        'img/fr.png',
        'img/ga.png',
        'img/gm.png',
        'img/ge.png',
        'img/de.png',
        'img/gh.png',
        'img/gr.png',
        'img/gd.png',
        'img/gt.png',
        'img/gn.png',
        'img/gw.png',
        'img/gy.png',
        'img/ht.png',
        'img/hn.png',
        'img/hu.png',
        'img/is.png',
        'img/in.png',
        'img/id.png',
        'img/ir.png',
        'img/iq.png',
        'img/ie.png',
        'img/il.png',
        'img/it.png',
        'img/jm.png',
        'img/jp.png',
        'img/jo.png',
        'img/kz.png',
        'img/ke.png',
        'img/ki.png',
        'img/kp.png',
        'img/kr.png',
        'img/kw.png',
        'img/kg.png',
        'img/la.png',
        'img/lv.png',
        'img/lb.png',
        'img/ls.png',
        'img/lr.png',
        'img/ly.png',
        'img/li.png',
        'img/lt.png',
        'img/lu.png',
        'img/mg.png',
        'img/mw.png',
        'img/my.png',
        'img/mv.png',
        'img/ml.png',
        'img/mt.png',
        'img/mh.png',
        'img/mr.png',
        'img/mu.png',
        'img/mx.png',
        'img/fm.png',
        'img/md.png',
        'img/mc.png',
        'img/mn.png',
        'img/me.png',
        'img/ma.png',
        'img/mz.png',
        'img/mm.png',
        'img/na.png',
        'img/nr.png',
        'img/np.png',
        'img/nl.png',
        'img/nz.png',
        'img/ni.png',
        'img/ne.png',
        'img/ng.png',
        'img/mk.png',
        'img/no.png',
        'img/om.png',
        'img/pk.png',
        'img/pw.png',
        'img/pa.png',
        'img/pg.png',
        'img/py.png',
        'img/pe.png',
        'img/ph.png',
        'img/pl.png',
        'img/pt.png',
        'img/qa.png',
        'img/ro.png',
        'img/ru.png',
        'img/rw.png',
        'img/kn.png',
        'img/lc.png',
        'img/vc.png',
        'img/ws.png',
        'img/sm.png',
        'img/st.png',
        'img/sa.png',
        'img/sn.png',
        'img/rs.png',
        'img/sc.png',
        'img/sl.png',
        'img/sg.png',
        'img/sk.png',
        'img/si.png',
        'img/sb.png',
        'img/so.png',
        'img/za.png',
        'img/ss.png',
        'img/es.png',
        'img/lk.png',
        'img/sd.png',
        'img/sr.png',
        'img/se.png',
        'img/ch.png',
        'img/sy.png',
        'img/tj.png',
        'img/tz.png',
        'img/th.png',
        'img/tl.png',
        'img/tg.png',
        'img/to.png',
        'img/tt.png',
        'img/tn.png',
        'img/tr.png',
        'img/tm.png',
        'img/tv.png', 
        'img/ug.png',
        'img/ua.png',
        'img/ae.png',
        'img/gb.png',
        'img/us.png',
        'img/uy.png',
        'img/uz.png',
        'img/vu.png',
        'img/ve.png',
        'img/vn.png',
        'img/ye.png',
        'img/zm.png',
        'img/zw.png'

        /*GO-E-MON-FORMAT
        context.getFileURL("af.png"),
        context.getFileURL("al.png"),
        context.getFileURL("dz.png"),
        context.getFileURL("ad.png"),
        context.getFileURL("ao.png"),
        context.getFileURL("ag.png"),
        context.getFileURL("ar.png"),
        context.getFileURL("am.png"),
        context.getFileURL("au.png"),
        context.getFileURL("at.png"),
        context.getFileURL("az.png"),
        context.getFileURL("bs.png"), 
        context.getFileURL("bh.png"),
        context.getFileURL("bd.png"),
        context.getFileURL("bb.png"),
        context.getFileURL("by.png"),
        context.getFileURL("be.png"),
        context.getFileURL("bz.png"),
        context.getFileURL("bj.png"),
        context.getFileURL("bt.png"),
        context.getFileURL("bo.png"),
        context.getFileURL("ba.png"),
        context.getFileURL("bw.png"),
        context.getFileURL("br.png"),
        context.getFileURL("bn.png"),
        context.getFileURL("bg.png"),
        context.getFileURL("bf.png"),
        context.getFileURL("bi.png"),
        context.getFileURL("kh.png"),
        context.getFileURL("cm.png"),
        context.getFileURL("ca.png"),
        context.getFileURL("cv.png"),
        context.getFileURL("cf.png"),
        context.getFileURL("td.png"),
        context.getFileURL("cl.png"),
        context.getFileURL("cn.png"),
        context.getFileURL("co.png"),
        context.getFileURL("km.png"),
        context.getFileURL("cg.png"),
        context.getFileURL("cd.png"),
        context.getFileURL("cr.png"),
        context.getFileURL("ci.png"),
        context.getFileURL("hr.png"),
        context.getFileURL("cu.png"),
        context.getFileURL("cy.png"),
        context.getFileURL("cz.png"),
        context.getFileURL("dk.png"),
        context.getFileURL("dj.png"),
        context.getFileURL("dm.png"),
        context.getFileURL("do.png"),
        context.getFileURL("ec.png"),
        context.getFileURL("eg.png"),
        context.getFileURL("sv.png"),
        context.getFileURL("gq.png"),
        context.getFileURL("er.png"),
        context.getFileURL("ee.png"),
        context.getFileURL("sz.png"),
        context.getFileURL("et.png"),
        context.getFileURL("fj.png"),
        context.getFileURL("fi.png"),
        context.getFileURL("fr.png"),
        context.getFileURL("ga.png"),
        context.getFileURL("gm.png"),
        context.getFileURL("ge.png"),
        context.getFileURL("de.png"),
        context.getFileURL("gh.png"),
        context.getFileURL("gr.png"),
        context.getFileURL("gd.png"),
        context.getFileURL("gt.png"),
        context.getFileURL("gn.png"),
        context.getFileURL("gw.png"),
        context.getFileURL("gy.png"),
        context.getFileURL("ht.png"),
        context.getFileURL("hn.png"),
        context.getFileURL("hu.png"),
        context.getFileURL("is.png"),
        context.getFileURL("in.png"),
        context.getFileURL("id.png"),
        context.getFileURL("ir.png"),
        context.getFileURL("iq.png"),
        context.getFileURL("ie.png"),
        context.getFileURL("il.png"),
        context.getFileURL("it.png"),
        context.getFileURL("jm.png"),
        context.getFileURL("jp.png"),
        context.getFileURL("jo.png"),
        context.getFileURL("kz.png"),
        context.getFileURL("ke.png"),
        context.getFileURL("ki.png"),
        context.getFileURL("kp.png"),
        context.getFileURL("kr.png"),
        context.getFileURL("kw.png"),
        context.getFileURL("kg.png"),
        context.getFileURL("la.png"),
        context.getFileURL("lv.png"),
        context.getFileURL("lb.png"),
        context.getFileURL("ls.png"),
        context.getFileURL("lr.png"),
        context.getFileURL("ly.png"),
        context.getFileURL("li.png"),
        context.getFileURL("lt.png"),
        context.getFileURL("lu.png"),
        context.getFileURL("mg.png"),
        context.getFileURL("mw.png"),
        context.getFileURL("my.png"),
        context.getFileURL("mv.png"),
        context.getFileURL("ml.png"),
        context.getFileURL("mt.png"),
        context.getFileURL("mh.png"),
        context.getFileURL("mr.png"),
        context.getFileURL("mu.png"),
        context.getFileURL("mx.png"),
        context.getFileURL("fm.png"),
        context.getFileURL("md.png"),
        context.getFileURL("mc.png"),
        context.getFileURL("mn.png"),
        context.getFileURL("me.png"),
        context.getFileURL("ma.png"),
        context.getFileURL("mz.png"),
        context.getFileURL("mm.png"),
        context.getFileURL("na.png"),
        context.getFileURL("nr.png"),
        context.getFileURL("np.png"),
        context.getFileURL("nl.png"),
        context.getFileURL("nz.png"),
        context.getFileURL("ni.png"),
        context.getFileURL("ne.png"),
        context.getFileURL("ng.png"),
        context.getFileURL("mk.png"),
        context.getFileURL("no.png"),
        context.getFileURL("om.png"),
        context.getFileURL("pk.png"),
        context.getFileURL("pw.png"),
        context.getFileURL("pa.png"),
        context.getFileURL("pg.png"),
        context.getFileURL("py.png"),
        context.getFileURL("pe.png"),
        context.getFileURL("ph.png"),
        context.getFileURL("pl.png"),
        context.getFileURL("pt.png"),
        context.getFileURL("qa.png"),
        context.getFileURL("ro.png"),
        context.getFileURL("ru.png"),
        context.getFileURL("rw.png"),
        context.getFileURL("kn.png"),
        context.getFileURL("lc.png"),
        context.getFileURL("vc.png"),
        context.getFileURL("ws.png"),
        context.getFileURL("sm.png"),
        context.getFileURL("st.png"),
        context.getFileURL("sa.png"),
        context.getFileURL("sn.png"),
        context.getFileURL("rs.png"),
        context.getFileURL("sc.png"),
        context.getFileURL("sl.png"),
        context.getFileURL("sg.png"),
        context.getFileURL("sk.png"),
        context.getFileURL("si.png"),
        context.getFileURL("sb.png"),
        context.getFileURL("so.png"),
        context.getFileURL("za.png"),
        context.getFileURL("ss.png"),
        context.getFileURL("es.png"),
        context.getFileURL("lk.png"),
        context.getFileURL("sd.png"),
        context.getFileURL("sr.png"),
        context.getFileURL("se.png"),
        context.getFileURL("ch.png"),
        context.getFileURL("sy.png"),
        context.getFileURL("tj.png"),
        context.getFileURL("tz.png"),
        context.getFileURL("th.png"),
        context.getFileURL("tl.png"),
        context.getFileURL("tg.png"),
        context.getFileURL("to.png"),
        context.getFileURL("tt.png"),
        context.getFileURL("tn.png"),
        context.getFileURL("tr.png"),
        context.getFileURL("tm.png"),
        context.getFileURL("tv.png"), 
        context.getFileURL("ug.png"),
        context.getFileURL("ua.png"),
        context.getFileURL("ae.png"),
        context.getFileURL("gb.png"),
        context.getFileURL("us.png"),
        context.getFileURL("uy.png"),
        context.getFileURL("uz.png"),
        context.getFileURL("vu.png"),
        context.getFileURL("ve.png"),
        context.getFileURL("vn.png"),
        context.getFileURL("ye.png"),
        context.getFileURL("zm.png"),
        context.getFileURL("zw.png")
        */
    ]
};
main_timeline.push(preload);


/*timeline variables*/
var variables = [
    /*STAND ALONE FORMAT */
    {picture: 'img/af.png', name: 'AFGHANISTAN'},
    {picture: 'img/al.png', name: 'ALBANIA'},
    {picture: 'img/dz.png', name: 'ALGERIA'},
    {picture: 'img/ad.png', name: 'ANDORRA'},
    {picture: 'img/ao.png', name: 'ANGOLA'},
    {picture: 'img/ag.png', name: 'ANTIGUA AND BARBUDA'},
    {picture: 'img/ar.png', name: 'ARGENTINA'},
    {picture: 'img/am.png', name: 'ARMENIA'},
    {picture: 'img/au.png', name: 'AUSTRALIA'},
    {picture: 'img/at.png', name: 'AUSTRIA'},
    {picture: 'img/az.png', name: 'AZERBAIJAN'},
    {picture: 'img/bs.png', name: 'BAHAMAS'}, //
    {picture: 'img/bh.png', name: 'BAHARAIN'},
    {picture: 'img/bd.png', name: 'BANGLADESH'},
    {picture: 'img/bb.png', name: 'BARBADOS'},
    {picture: 'img/by.png', name: 'BELARUS'},
    {picture: 'img/be.png', name: 'BELGIUM'},
    {picture: 'img/bz.png', name: 'BELIZE'},
    {picture: 'img/bj.png', name: 'BENIN'},
    {picture: 'img/bt.png', name: 'BHUTAN'},
    {picture: 'img/bo.png', name: 'BOLIVIA'},
    {picture: 'img/ba.png', name: 'BOSNIA AND HERZEGOVINA'},
    {picture: 'img/bw.png', name: 'BOTSWANA'},
    {picture: 'img/br.png', name: 'BRAZIL'},
    {picture: 'img/bn.png', name: 'BRUNEI'},
    {picture: 'img/bg.png', name: 'BULGARIA'},
    {picture: 'img/bf.png', name: 'BURKINA FASO'},
    {picture: 'img/bi.png', name: 'BURUNDI'},
    {picture: 'img/kh.png', name: 'CAMBODIA'},
    {picture: 'img/cm.png', name: 'CAMEROON'},
    {picture: 'img/ca.png', name: 'CANADA'},
    {picture: 'img/cv.png', name: 'CAPE VERDE'},
    {picture: 'img/cf.png', name: 'CENTRAL AFRICAN REPUBLIC'},
    {picture: 'img/td.png', name: 'CHAD'},
    {picture: 'img/cl.png', name: 'CHILE'},
    {picture: 'img/cn.png', name: 'CHINA'},//
    {picture: 'img/co.png', name: 'COLOMBIA'},
    {picture: 'img/km.png', name: 'COMOROS'},
    {picture: 'img/cg.png', name: 'REPUBLIC OF THE CONGO'},
    {picture: 'img/cd.png', name: 'DR CONGO'},
    {picture: 'img/cr.png', name: 'COSTA RICA'},
    {picture: 'img/ci.png', name: 'IVORY COAST'},
    {picture: 'img/hr.png', name: 'CROATIA'},
    {picture: 'img/cu.png', name: 'CUBA'},
    {picture: 'img/cy.png', name: 'CYPRUS'},
    {picture: 'img/cz.png', name: 'CZECHIA'},
    {picture: 'img/dk.png', name: 'DENMARK'},
    {picture: 'img/dj.png', name: 'DJIBOUTI'},
    {picture: 'img/dm.png', name: 'DOMINICA'},
    {picture: 'img/do.png', name: 'DOMINICAN REPUBLIC'},
    {picture: 'img/ec.png', name: 'ECUADOR'},
    {picture: 'img/eg.png', name: 'EGYPT'},
    {picture: 'img/sv.png', name: 'EL SALVADOR'},
    {picture: 'img/gq.png', name: 'EQUATORIAL GUINEA'},
    {picture: 'img/er.png', name: 'ERITREA'},
    {picture: 'img/ee.png', name: 'ESTONIA'},
    {picture: 'img/sz.png', name: 'ESWATINI'},
    {picture: 'img/et.png', name: 'ETHIOPIA'},
    {picture: 'img/fj.png', name: 'FIJI'},
    {picture: 'img/fi.png', name: 'FINLAND'},//
    {picture: 'img/fr.png', name: 'FRANCE'},
    {picture: 'img/ga.png', name: 'GABON'},
    {picture: 'img/gm.png', name: 'GAMBIA'},
    {picture: 'img/ge.png', name: 'GEORGIA'},
    {picture: 'img/de.png', name: 'GERMANY'},
    {picture: 'img/gh.png', name: 'GHANA'},
    {picture: 'img/gr.png', name: 'GREECE'},
    {picture: 'img/gd.png', name: 'GRENADA'},
    {picture: 'img/gt.png', name: 'GUATEMALA'},
    {picture: 'img/gn.png', name: 'GUINEA'},
    {picture: 'img/gw.png', name: 'GUINEA-BISSAU'},
    {picture: 'img/gy.png', name: 'GUYANA'},
    {picture: 'img/ht.png', name: 'HAITI'},
    {picture: 'img/hn.png', name: 'HONDURAS'},
    {picture: 'img/hu.png', name: 'HUNGARY'},
    {picture: 'img/is.png', name: 'ICELAND'},
    {picture: 'img/in.png', name: 'INDIA'},
    {picture: 'img/id.png', name: 'INDONESIA'},
    {picture: 'img/ir.png', name: 'IRAN'},
    {picture: 'img/iq.png', name: 'IRAQ'},
    {picture: 'img/ie.png', name: 'IRELAND'},
    {picture: 'img/il.png', name: 'ISRAEL'},
    {picture: 'img/it.png', name: 'ITALY'},
    {picture: 'img/jm.png', name: 'JAMAICA'},//
    {picture: 'img/jp.png', name: 'JAPAN'},
    {picture: 'img/jo.png', name: 'JORDAN'},
    {picture: 'img/kz.png', name: 'KAZAKHSTAN'},
    {picture: 'img/ke.png', name: 'KENYA'},
    {picture: 'img/ki.png', name: 'KIRIBATI'},
    {picture: 'img/kp.png', name: 'NORTH KOREA'},
    {picture: 'img/kr.png', name: 'SOUTH KOREA'},
    {picture: 'img/kw.png', name: 'KUWAIT'},
    {picture: 'img/kg.png', name: 'KYRGYZSTAN'},
    {picture: 'img/la.png', name: 'LAOS'},
    {picture: 'img/lv.png', name: 'LATVIA'},
    {picture: 'img/lb.png', name: 'LEBANON'},
    {picture: 'img/ls.png', name: 'LESOTHO'},
    {picture: 'img/lr.png', name: 'LIBERIA'},
    {picture: 'img/ly.png', name: 'LIBYA'},
    {picture: 'img/li.png', name: 'LIECHTENSTEIN'},
    {picture: 'img/lt.png', name: 'LITHUANIA'},
    {picture: 'img/lu.png', name: 'LUXENBOURG'},
    {picture: 'img/mg.png', name: 'MADAGASCAR'},
    {picture: 'img/mw.png', name: 'MALAWI'},
    {picture: 'img/my.png', name: 'MALAYSIA'},
    {picture: 'img/mv.png', name: 'MALDIVES'},
    {picture: 'img/ml.png', name: 'MALI'},
    {picture: 'img/mt.png', name: 'MALTA'},//
    {picture: 'img/mh.png', name: 'MARSHALL ISLANDS'},
    {picture: 'img/mr.png', name: 'MAURITANIA'},
    {picture: 'img/mu.png', name: 'MAURITIUS'},
    {picture: 'img/mx.png', name: 'MEXICO'},
    {picture: 'img/fm.png', name: 'MICRONESIA'},
    {picture: 'img/md.png', name: 'MOLDOVA'},
    {picture: 'img/mc.png', name: 'MONACO'},
    {picture: 'img/mn.png', name: 'MONGOLIA'},
    {picture: 'img/me.png', name: 'MONTENEGRO'},
    {picture: 'img/ma.png', name: 'MOROCCO'},
    {picture: 'img/mz.png', name: 'MOZAMBIQUE'},
    {picture: 'img/mm.png', name: 'MYANMAR'},
    {picture: 'img/na.png', name: 'NAMIBIA'},
    {picture: 'img/nr.png', name: 'NAURU'},
    {picture: 'img/np.png', name: 'NEPAL'},
    {picture: 'img/nl.png', name: 'NETHERLANDS'},
    {picture: 'img/nz.png', name: 'NEW ZEALAND'},
    {picture: 'img/ni.png', name: 'NICARAGUA'},
    {picture: 'img/ne.png', name: 'NIGER'},
    {picture: 'img/ng.png', name: 'NIGERIA'},
    {picture: 'img/mk.png', name: 'NORTH MACEDONIA'},
    {picture: 'img/no.png', name: 'NORWAY'},
    {picture: 'img/om.png', name: 'OMAN'},
    {picture: 'img/pk.png', name: 'PAKISTAN'},//
    {picture: 'img/pw.png', name: 'PALAU'},
    {picture: 'img/pa.png', name: 'PANAMA'},
    {picture: 'img/pg.png', name: 'PAPUA NEW GUINEA'},
    {picture: 'img/py.png', name: 'PARAGUAY'},
    {picture: 'img/pe.png', name: 'PERU'},
    {picture: 'img/ph.png', name: 'PHILIPINES'},
    {picture: 'img/pl.png', name: 'POLAND'},
    {picture: 'img/pt.png', name: 'PORTUGAL'},
    {picture: 'img/qa.png', name: 'QATAR'},
    {picture: 'img/ro.png', name: 'ROMANIA'},
    {picture: 'img/ru.png', name: 'RUSSIA'},
    {picture: 'img/rw.png', name: 'RWANDA'},
    {picture: 'img/kn.png', name: 'SAINT KITTS AND NEVIS'},
    {picture: 'img/lc.png', name: 'SAINT LUCIA'},
    {picture: 'img/vc.png', name: 'SAINT VINCENT AND THE GRENADINES'},
    {picture: 'img/ws.png', name: 'SAMOA'},
    {picture: 'img/sm.png', name: 'SAN MARINO'},
    {picture: 'img/st.png', name: 'SAO TOME AND PRINCIPE'},
    {picture: 'img/sa.png', name: 'SAUDI ARABIA'},
    {picture: 'img/sn.png', name: 'SENEGAL'},
    {picture: 'img/rs.png', name: 'SERBIA'},
    {picture: 'img/sc.png', name: 'SEYCHELLES'},
    {picture: 'img/sl.png', name: 'SIERRA LEONE'},
    {picture: 'img/sg.png', name: 'SINGAPORE'},//
    {picture: 'img/sk.png', name: 'SLOVAKIA'},
    {picture: 'img/si.png', name: 'SLOVENIA'},
    {picture: 'img/sb.png', name: 'SOLOMON ISLANDS'},
    {picture: 'img/so.png', name: 'SOMALIA'},
    {picture: 'img/za.png', name: 'SOUTH AFRICA'},
    {picture: 'img/ss.png', name: 'SOUTH SUDAN'},
    {picture: 'img/es.png', name: 'SPAIN'},
    {picture: 'img/lk.png', name: 'SRI LANKA'},
    {picture: 'img/sd.png', name: 'SUDAN'},
    {picture: 'img/sr.png', name: 'SURINAME'},
    {picture: 'img/se.png', name: 'SWEEDEN'},
    {picture: 'img/ch.png', name: 'SWITZERLAND'},
    {picture: 'img/sy.png', name: 'SYRIA'},
    {picture: 'img/tj.png', name: 'TAJIKISTAN'},
    {picture: 'img/tz.png', name: 'TANZANIA'},
    {picture: 'img/th.png', name: 'THAILAND'},
    {picture: 'img/tl.png', name: 'TIMOR-LESTE'},
    {picture: 'img/tg.png', name: 'TOGO'},
    {picture: 'img/to.png', name: 'TONGA'},
    {picture: 'img/tt.png', name: 'TRINIDAD AND TOBAGO'},
    {picture: 'img/tn.png', name: 'TUNISIA'},
    {picture: 'img/tr.png', name: 'TURKEY'},
    {picture: 'img/tm.png', name: 'TURKMENISTAN'},
    {picture: 'img/tv.png', name: 'TUVALU'}, //
    {picture: 'img/ug.png', name: 'UGANDA'},
    {picture: 'img/ua.png', name: 'UKRAINE'},
    {picture: 'img/ae.png', name: 'UNITED ARAB EMIRATES'},
    {picture: 'img/gb.png', name: 'UNITED KINGDOM'},
    {picture: 'img/us.png', name: 'UNITED STATES'},
    {picture: 'img/uy.png', name: 'URUGUAY'},
    {picture: 'img/uz.png', name: 'UZBEKISTAN'},
    {picture: 'img/vu.png', name: 'VANUATU'},
    {picture: 'img/ve.png', name: 'VENEZUELA'},
    {picture: 'img/vn.png', name: 'VIETNAM'},
    {picture: 'img/ye.png', name: 'YEMEN'},
    {picture: 'img/zm.png', name: 'ZAMBIA'},
    {picture: 'img/zw.png', name: 'ZIMBABWE'}   
    
    /* GO-E-MON FORMAT 
    {picture: context.getFileURL("af.png"), name: 'AFGHANISTAN'},
    {picture: context.getFileURL("al.png"), name: 'ALBANIA'},
    {picture: context.getFileURL("dz.png"), name: 'ALGERIA'},
    {picture: context.getFileURL("ad.png"), name: 'ANDORRA'},
    {picture: context.getFileURL("ao.png"), name: 'ANGOLA'},
    {picture: context.getFileURL("ag.png"), name: 'ANTIGUA AND BARBUDA'},
    {picture: context.getFileURL("ar.png"), name: 'ARGENTINA'},
    {picture: context.getFileURL("am.png"), name: 'ARMENIA'},
    {picture: context.getFileURL("au.png"), name: 'AUSTRALIA'},
    {picture: context.getFileURL("at.png"), name: 'AUSTRIA'},
    {picture: context.getFileURL("az.png"), name: 'AZERBAIJAN'},
    {picture: context.getFileURL("bs.png"), name: 'BAHAMAS'}, //
    {picture: context.getFileURL("bh.png"), name: 'BAHARAIN'},
    {picture: context.getFileURL("bd.png"), name: 'BANGLADESH'},
    {picture: context.getFileURL("bb.png"), name: 'BARBADOS'},
    {picture: context.getFileURL("by.png"), name: 'BELARUS'},
    {picture: context.getFileURL("be.png"), name: 'BELGIUM'},
    {picture: context.getFileURL("bz.png"), name: 'BELIZE'},
    {picture: context.getFileURL("bj.png"), name: 'BENIN'},
    {picture: context.getFileURL("bt.png"), name: 'BHUTAN'},
    {picture: context.getFileURL("bo.png"), name: 'BOLIVIA'},
    {picture: context.getFileURL("ba.png"), name: 'BOSNIA AND HERZEGOVINA'},
    {picture: context.getFileURL("bw.png"), name: 'BOTSWANA'},
    {picture: context.getFileURL("br.png"), name: 'BRAZIL'},
    {picture: context.getFileURL("bn.png"), name: 'BRUNEI'},
    {picture: context.getFileURL("bg.png"), name: 'BULGARIA'},
    {picture: context.getFileURL("bf.png"), name: 'BURKINA FASO'},
    {picture: context.getFileURL("bi.png"), name: 'BURUNDI'},
    {picture: context.getFileURL("kh.png"), name: 'CAMBODIA'},
    {picture: context.getFileURL("cm.png"), name: 'CAMEROON'},
    {picture: context.getFileURL("ca.png"), name: 'CANADA'},
    {picture: context.getFileURL("cv.png"), name: 'CAPE VERDE'},
    {picture: context.getFileURL("cf.png"), name: 'CENTRAL AFRICAN REPUBLIC'},
    {picture: context.getFileURL("td.png"), name: 'CHAD'},
    {picture: context.getFileURL("cl.png"), name: 'CHILE'},
    {picture: context.getFileURL("cn.png"), name: 'CHINA'},//
    {picture: context.getFileURL("co.png"), name: 'COLOMBIA'},
    {picture: context.getFileURL("km.png"), name: 'COMOROS'},
    {picture: context.getFileURL("cg.png"), name: 'REPUBLIC OF THE CONGO'},
    {picture: context.getFileURL("cd.png"), name: 'DR CONGO'},
    {picture: context.getFileURL("cr.png"), name: 'COSTA RICA'},
    {picture: context.getFileURL("ci.png"), name: 'IVORY COAST'},
    {picture: context.getFileURL("hr.png"), name: 'CROATIA'},
    {picture: context.getFileURL("cu.png"), name: 'CUBA'},
    {picture: context.getFileURL("cy.png"), name: 'CYPRUS'},
    {picture: context.getFileURL("cz.png"), name: 'CZECHIA'},
    {picture: context.getFileURL("dk.png"), name: 'DENMARK'},
    {picture: context.getFileURL("dj.png"), name: 'DJIBOUTI'},
    {picture: context.getFileURL("dm.png"), name: 'DOMINICA'},
    {picture: context.getFileURL("do.png"), name: 'DOMINICAN REPUBLIC'},
    {picture: context.getFileURL("ec.png"), name: 'ECUADOR'},
    {picture: context.getFileURL("eg.png"), name: 'EGYPT'},
    {picture: context.getFileURL("sv.png"), name: 'EL SALVADOR'},
    {picture: context.getFileURL("gq.png"), name: 'EQUATORIAL GUINEA'},
    {picture: context.getFileURL("er.png"), name: 'ERITREA'},
    {picture: context.getFileURL("ee.png"), name: 'ESTONIA'},
    {picture: context.getFileURL("sz.png"), name: 'ESWATINI'},
    {picture: context.getFileURL("et.png"), name: 'ETHIOPIA'},
    {picture: context.getFileURL("fj.png"), name: 'FIJI'},
    {picture: context.getFileURL("fi.png"), name: 'FINLAND'},//
    {picture: context.getFileURL("fr.png"), name: 'FRANCE'},
    {picture: context.getFileURL("ga.png"), name: 'GABON'},
    {picture: context.getFileURL("gm.png"), name: 'GAMBIA'},
    {picture: context.getFileURL("ge.png"), name: 'GEORGIA'},
    {picture: context.getFileURL("de.png"), name: 'GERMANY'},
    {picture: context.getFileURL("gh.png"), name: 'GHANA'},
    {picture: context.getFileURL("gr.png"), name: 'GREECE'},
    {picture: context.getFileURL("gd.png"), name: 'GRENADA'},
    {picture: context.getFileURL("gt.png"), name: 'GUATEMALA'},
    {picture: context.getFileURL("gn.png"), name: 'GUINEA'},
    {picture: context.getFileURL("gw.png"), name: 'GUINEA-BISSAU'},
    {picture: context.getFileURL("gy.png"), name: 'GUYANA'},
    {picture: context.getFileURL("ht.png"), name: 'HAITI'},
    {picture: context.getFileURL("hn.png"), name: 'HONDURAS'},
    {picture: context.getFileURL("hu.png"), name: 'HUNGARY'},
    {picture: context.getFileURL("is.png"), name: 'ICELAND'},
    {picture: context.getFileURL("in.png"), name: 'INDIA'},
    {picture: context.getFileURL("id.png"), name: 'INDONESIA'},
    {picture: context.getFileURL("ir.png"), name: 'IRAN'},
    {picture: context.getFileURL("iq.png"), name: 'IRAQ'},
    {picture: context.getFileURL("ie.png"), name: 'IRELAND'},
    {picture: context.getFileURL("il.png"), name: 'ISRAEL'},
    {picture: context.getFileURL("it.png"), name: 'ITALY'},
    {picture: context.getFileURL("jm.png"), name: 'JAMAICA'},//
    {picture: context.getFileURL("jp.png"), name: 'JAPAN'},
    {picture: context.getFileURL("jo.png"), name: 'JORDAN'},
    {picture: context.getFileURL("kz.png"), name: 'KAZAKHSTAN'},
    {picture: context.getFileURL("ke.png"), name: 'KENYA'},
    {picture: context.getFileURL("ki.png"), name: 'KIRIBATI'},
    {picture: context.getFileURL("kp.png"), name: 'NORTH KOREA'},
    {picture: context.getFileURL("kr.png"), name: 'SOUTH KOREA'},
    {picture: context.getFileURL("kw.png"), name: 'KUWAIT'},
    {picture: context.getFileURL("kg.png"), name: 'KYRGYZSTAN'},
    {picture: context.getFileURL("la.png"), name: 'LAOS'},
    {picture: context.getFileURL("lv.png"), name: 'LATVIA'},
    {picture: context.getFileURL("lb.png"), name: 'LEBANON'},
    {picture: context.getFileURL("ls.png"), name: 'LESOTHO'},
    {picture: context.getFileURL("lr.png"), name: 'LIBERIA'},
    {picture: context.getFileURL("ly.png"), name: 'LIBYA'},
    {picture: context.getFileURL("li.png"), name: 'LIECHTENSTEIN'},
    {picture: context.getFileURL("lt.png"), name: 'LITHUANIA'},
    {picture: context.getFileURL("lu.png"), name: 'LUXENBOURG'},
    {picture: context.getFileURL("mg.png"), name: 'MADAGASCAR'},
    {picture: context.getFileURL("mw.png"), name: 'MALAWI'},
    {picture: context.getFileURL("my.png"), name: 'MALAYSIA'},
    {picture: context.getFileURL("mv.png"), name: 'MALDIVES'},
    {picture: context.getFileURL("ml.png"), name: 'MALI'},
    {picture: context.getFileURL("mt.png"), name: 'MALTA'},//
    {picture: context.getFileURL("mh.png"), name: 'MARSHALL ISLANDS'},
    {picture: context.getFileURL("mr.png"), name: 'MAURITANIA'},
    {picture: context.getFileURL("mu.png"), name: 'MAURITIUS'},
    {picture: context.getFileURL("mx.png"), name: 'MEXICO'},
    {picture: context.getFileURL("fm.png"), name: 'MICRONESIA'},
    {picture: context.getFileURL("md.png"), name: 'MOLDOVA'},
    {picture: context.getFileURL("mc.png"), name: 'MONACO'},
    {picture: context.getFileURL("mn.png"), name: 'MONGOLIA'},
    {picture: context.getFileURL("me.png"), name: 'MONTENEGRO'},
    {picture: context.getFileURL("ma.png"), name: 'MOROCCO'},
    {picture: context.getFileURL("mz.png"), name: 'MOZAMBIQUE'},
    {picture: context.getFileURL("mm.png"), name: 'MYANMAR'},
    {picture: context.getFileURL("na.png"), name: 'NAMIBIA'},
    {picture: context.getFileURL("nr.png"), name: 'NAURU'},
    {picture: context.getFileURL("np.png"), name: 'NEPAL'},
    {picture: context.getFileURL("nl.png"), name: 'NETHERLANDS'},
    {picture: context.getFileURL("nz.png"), name: 'NEW ZEALAND'},
    {picture: context.getFileURL("ni.png"), name: 'NICARAGUA'},
    {picture: context.getFileURL("ne.png"), name: 'NIGER'},
    {picture: context.getFileURL("ng.png"), name: 'NIGERIA'},
    {picture: context.getFileURL("mk.png"), name: 'NORTH MACEDONIA'},
    {picture: context.getFileURL("no.png"), name: 'NORWAY'},
    {picture: context.getFileURL("om.png"), name: 'OMAN'},
    {picture: context.getFileURL("pk.png"), name: 'PAKISTAN'},//
    {picture: context.getFileURL("pw.png"), name: 'PALAU'},
    {picture: context.getFileURL("pa.png"), name: 'PANAMA'},
    {picture: context.getFileURL("pg.png"), name: 'PAPUA NEW GUINEA'},
    {picture: context.getFileURL("py.png"), name: 'PARAGUAY'},
    {picture: context.getFileURL("pe.png"), name: 'PERU'},
    {picture: context.getFileURL("ph.png"), name: 'PHILIPINES'},
    {picture: context.getFileURL("pl.png"), name: 'POLAND'},
    {picture: context.getFileURL("pt.png"), name: 'PORTUGAL'},
    {picture: context.getFileURL("qa.png"), name: 'QATAR'},
    {picture: context.getFileURL("ro.png"), name: 'ROMANIA'},
    {picture: context.getFileURL("ru.png"), name: 'RUSSIA'},
    {picture: context.getFileURL("rw.png"), name: 'RWANDA'},
    {picture: context.getFileURL("kn.png"), name: 'SAINT KITTS AND NEVIS'},
    {picture: context.getFileURL("lc.png"), name: 'SAINT LUCIA'},
    {picture: context.getFileURL("vc.png"), name: 'SAINT VINCENT AND THE GRENADINES'},
    {picture: context.getFileURL("ws.png"), name: 'SAMOA'},
    {picture: context.getFileURL("sm.png"), name: 'SAN MARINO'},
    {picture: context.getFileURL("st.png"), name: 'SAO TOME AND PRINCIPE'},
    {picture: context.getFileURL("sa.png"), name: 'SAUDI ARABIA'},
    {picture: context.getFileURL("sn.png"), name: 'SENEGAL'},
    {picture: context.getFileURL("rs.png"), name: 'SERBIA'},
    {picture: context.getFileURL("sc.png"), name: 'SEYCHELLES'},
    {picture: context.getFileURL("sl.png"), name: 'SIERRA LEONE'},
    {picture: context.getFileURL("sg.png"), name: 'SINGAPORE'},//
    {picture: context.getFileURL("sk.png"), name: 'SLOVAKIA'},
    {picture: context.getFileURL("si.png"), name: 'SLOVENIA'},
    {picture: context.getFileURL("sb.png"), name: 'SOLOMON ISLANDS'},
    {picture: context.getFileURL("so.png"), name: 'SOMALIA'},
    {picture: context.getFileURL("za.png"), name: 'SOUTH AFRICA'},
    {picture: context.getFileURL("ss.png"), name: 'SOUTH SUDAN'},
    {picture: context.getFileURL("es.png"), name: 'SPAIN'},
    {picture: context.getFileURL("lk.png"), name: 'SRI LANKA'},
    {picture: context.getFileURL("sd.png"), name: 'SUDAN'},
    {picture: context.getFileURL("sr.png"), name: 'SURINAME'},
    {picture: context.getFileURL("se.png"), name: 'SWEEDEN'},
    {picture: context.getFileURL("ch.png"), name: 'SWITZERLAND'},
    {picture: context.getFileURL("sy.png"), name: 'SYRIA'},
    {picture: context.getFileURL("tj.png"), name: 'TAJIKISTAN'},
    {picture: context.getFileURL("tz.png"), name: 'TANZANIA'},
    {picture: context.getFileURL("th.png"), name: 'THAILAND'},
    {picture: context.getFileURL("tl.png"), name: 'TIMOR-LESTE'},
    {picture: context.getFileURL("tg.png"), name: 'TOGO'},
    {picture: context.getFileURL("to.png"), name: 'TONGA'},
    {picture: context.getFileURL("tt.png"), name: 'TRINIDAD AND TOBAGO'},
    {picture: context.getFileURL("tn.png"), name: 'TUNISIA'},
    {picture: context.getFileURL("tr.png"), name: 'TURKEY'},
    {picture: context.getFileURL("tm.png"), name: 'TURKMENISTAN'},
    {picture: context.getFileURL("tv.png"), name: 'TUVALU'}, //
    {picture: context.getFileURL("ug.png"), name: 'UGANDA'},
    {picture: context.getFileURL("ua.png"), name: 'UKRAINE'},
    {picture: context.getFileURL("ae.png"), name: 'UNITED ARAB EMIRATES'},
    {picture: context.getFileURL("gb.png"), name: 'UNITED KINGDOM'},
    {picture: context.getFileURL("us.png"), name: 'UNITED STATES'},
    {picture: context.getFileURL("uy.png"), name: 'URUGUAY'},
    {picture: context.getFileURL("uz.png"), name: 'UZBEKISTAN'},
    {picture: context.getFileURL("vu.png"), name: 'VANUATU'},
    {picture: context.getFileURL("ve.png"), name: 'VENEZUELA'},
    {picture: context.getFileURL("vn.png"), name: 'VIETNAM'},
    {picture: context.getFileURL("ye.png"), name: 'YEMEN'},
    {picture: context.getFileURL("zm.png"), name: 'ZAMBIA'},
    {picture: context.getFileURL("zw.png"), name: 'ZIMBABWE'},*/
];      

/*The first trial will be a simple welcome message using the html-kbeyboard-response plugin.*/   
var welcome = {
    type: jsPsychHtmlButtonResponse,
    stimulus: `<div style="font-size:32px;">
               <p>Welcome to the experiment.</p> 
               <p>Tap "START" to begin.</p>
               </div>`,
    choices: ['START']
};
main_timeline.push(welcome); 

var learn_instructions = {
    type: jsPsychHtmlButtonResponse,
    stimulus: `
    <div style="font-size:24px;">
    <p>In this part of the experiment, you will be shown a random set of flags corresponding to UN member countries followed by their names.</p>
    <p>Each flag will rappear 3 times randomly, so you are able to associate the flag to the right country.</p>
    <p>After this session, you will be shown a flag and check if you are able to remember the right name of the country.</p>
    <div style='float: center;'><img src='${context.getFileURL("jp.png")}' width="640" height="480"></img>   
    </div>
    <p>Tap "START" to begin.</p>
    </div>
    `,
    choices: ['START'],
    post_trial_gap: 250
};
main_timeline.push(learn_instructions);

//create new list whit shuffled elements, the second argument indicates the number of repetitions
var repeated_variables = jsPsych.randomization.repeat(variables,1);

//Initially, the picture will be shown
var trial_pic = {
   type: jsPsychImageKeyboardResponse,   
   stimulus: jsPsych.timelineVariable("picture"),
   stimulus_width: 640,
   stimulus_height: 480,
   trial_duration: 1000,  
   response_ends_trial: false 
};  

//The picture is followed by the name of the item
var trial_name = {
    type: jsPsychHtmlKeyboardResponse,   
    stimulus: function (){
        return `<div style="font-size:72px;">${jsPsych.timelineVariable ("name")}</div>`;
    }, 
    trial_duration: 1000,
    response_ends_trial: false  
}; 

//Fixation cross inbetween trials 
var fixation = {
    type: jsPsychHtmlKeyboardResponse,
    stimulus: '<div style="font-size:96px;">+</div>',
    choices: "NO_KEYS",
    trial_duration: function(){
       return jsPsych.randomization.sampleWithoutReplacement([500, 750, 1000, 1250, 1500, 1750, 2000], 1)[0];
      }, 
    data: {
	    task: 'fixation'
	  }
}; 

var flashcard_study = {
   timeline: [trial_pic,trial_name,fixation],
   timeline_variables: repeated_variables,   
};
main_timeline.push(flashcard_study);

var rest = {
    type: jsPsychHtmlKeyboardResponse,
    stimulus: '<div style="font-size:32px;">Please wait a moment...you can take a short break</div>',
    choices: "NO_KEYS",
    trial_duration: 2000	  
};
main_timeline.push(rest);

var recog_instructions = {
    type: jsPsychHtmlButtonResponse,
    stimulus: `
    <div style="font-size:24px;">
    <p>Now you will be asked if you remember the right name of the animal shown before.</p>
    <p>Each animal picture will be shown once and you will click YES if you remember the right name of the animal or NO if you do not.</p>
    <p>Right after, you will be asked if you are confident on the name of the animal. Please click "Completely" if you are absolute sure 
    you can remember, "Barely" if you cannot remember the right name or "Just Guessing if you are not sure your answer is right".</p>
    <p>Tap "START" to begin.</p>
    </div>
    `,
    choices: ['START'],
    post_trial_gap: 1000
};
main_timeline.push(recog_instructions);

//pre if
var trial_test = {
    type: jsPsychImageButtonResponse,
    stimulus: jsPsych.timelineVariable("picture"),
    stimulus_width: 640,
    stimulus_height: 480,
    choices: ['Yes', 'No'],
    prompt:  `
    <div style="font-size:24px;">
    <p>Can you name this animal?</p>
    </div>`
};

//if trial
var confidence = { 
    type: jsPsychImageButtonResponse,
    stimulus: jsPsych.timelineVariable("picture"),
    stimulus_width: 640,
    stimulus_height: 480,    
    choices: ['Completely', 'Just Guessing'],
    prompt: `<div style="font-size:24px;">
    <p>How confident do you feel about your decission?</p>
    </div>`
};

var if_node = {
  timeline: [confidence],
  conditional_function: function (){
    var data = jsPsych.data.get().last(1).values()[0];
    console.log(data); 
    if (data.response == 0){
      return true;
    }else {
      return false;
    }
  }
};

//after if
var feedback = { 
    type: jsPsychImageKeyboardResponse,   
    stimulus: jsPsych.timelineVariable("picture"),
    stimulus_width: 640,
    stimulus_height: 480,       
    trial_duration: 1000,
    //${jsPsych.timelineVariable ("name")}
    prompt: function (){
        return `
        <div style="font-size:24px;"><p>The right answer is:</p></div>
        <div style="font-size:42px;"><p>${jsPsych.timelineVariable ("name")}</p></div>`;
    },
    response_ends_trial: false  
}; 

var randomized_variables = jsPsych.randomization.repeat(variables,1);

var recognition_test = {
  timeline: [trial_test,if_node,feedback,fixation],
  //timeline: [trial_test,feedback,fixation],
  timeline_variables: randomized_variables, 
};
main_timeline.push(recognition_test);

var finalization = {
    type: jsPsychHtmlKeyboardResponse,
    stimulus: `
    <div style="font-size:48px;">
    <p>This is the end of the experiment.</p>
    <p>Thank you very much for your participation.</p>
    </div>`,
    post_trial_gap: 500
};
main_timeline.push(finalization);

/*Run experiment*/
context.appMenu.hide();
//jsPsych.run([gb].concat(trials));
jsPsych.run(main_timeline);
